### PR TITLE
feat: add install vela api

### PR DESCRIPTION
**Pull request by qingfengming**

### CODE REVIEW

**Comment by qingfengming** [comment]
不好意思，之前看到依赖cluster接口，写的慢了些。快写完了才看到指给别人了，还是提一下吧，说不定可以参考一下。

**Review by hongchaodeng — APPROVED** [review]
lgtm

**Comment by hongchaodeng** [comment]
CI 修一下：
```
# github.com/oam-dev/velacp/pkg/rest/services
pkg/rest/services/velainstall.go:74:12: Sprintf format %s has arg version of wrong type int
pkg/rest/services/velainstall.go:151:11: Errorf format %s reads arg #2, but call has 1 arg
pkg/rest/services/velainstall.go:190:13: Errorf format %s reads arg #2, but call has 1 arg
```

**Comment by qingfengming** [comment]
> CI 修一下：
> 
> ```
> # github.com/oam-dev/velacp/pkg/rest/services
> pkg/rest/services/velainstall.go:74:12: Sprintf format %s has arg version of wrong type int
> pkg/rest/services/velainstall.go:151:11: Errorf format %s reads arg #2, but call has 1 arg
> pkg/rest/services/velainstall.go:190:13: Errorf format %s reads arg #2, but call has 1 arg
> ```

Done

**Review by hongchaodeng — APPROVED** [review]
Nice work! LGTM

**Comment by hongchaodeng** [comment]
Thank you very much for your contribution!

**Pull request merged**
